services:
  - type: web
    name: medjaouri-travel
    runtime: static
    buildCommand: "echo Static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
